<?php
// shop/product-detail-data.php

$productDetails = [
    [
        'id' => 1,
        'name' => 'AMD Ryzen 9 7950X 16-Core Processor',
        'brand' => 'AMD',
        'category' => 'Processors',
        'price' => 549.99,
        'old_price' => 699.99,
        'rating' => 4.8,
        'reviews' => 2847,
        'stock' => 45,
        'free_shipping' => true,
        'badge' => 'HOT',
        'images' => [
            'https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?w=800',
            'https://images.unsplash.com/photo-1555617981-dac3880eac6e?w=800',
            'https://images.unsplash.com/photo-1562976540-1502c2145186?w=800',
            'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800',
        ],
        'description' => 'Experience unprecedented performance with the AMD Ryzen 9 7950X. Built on the advanced Zen 4 architecture, this powerhouse processor delivers exceptional speed and efficiency for gaming, content creation, and demanding workloads. With 16 cores and 32 threads, it handles multitasking with ease while maintaining low power consumption.',
        'features' => [
            '16 Cores, 32 Threads for ultimate multitasking',
            'Base Clock: 4.5 GHz, Max Boost: 5.7 GHz',
            '80MB Total Cache (64MB L3 + 16MB L2)',
            'Socket AM5 with DDR5 and PCIe 5.0 support',
            'AMD 3D V-Cache™ Technology Ready',
            'Unlocked for overclocking',
            '170W TDP with efficient power management',
            'Integrated Radeon Graphics',
            'Support for AMD EXPO™ Technology',
            'Compatible with 600 Series Chipsets'
        ],
        'specifications' => [
            'Model' => 'AMD Ryzen 9 7950X',
            'Cores' => '16',
            'Threads' => '32',
            'Base Clock' => '4.5 GHz',
            'Max Boost Clock' => '5.7 GHz',
            'Total Cache' => '80 MB',
            'Socket' => 'AM5',
            'TDP' => '170W',
            'Memory Support' => 'DDR5-5200',
            'PCIe Version' => 'PCIe 5.0',
            'Graphics' => 'Integrated Radeon',
            'Cooler Included' => 'No (sold separately)',
            'Manufacturing Process' => '5nm',
            'Warranty' => '3 Years'
        ]
    ],
    [
        'id' => 2,
        'name' => 'NVIDIA GeForce RTX 4090 24GB Graphics Card',
        'brand' => 'NVIDIA',
        'category' => 'Graphics Cards',
        'price' => 1599.99,
        'old_price' => 1899.99,
        'rating' => 4.9,
        'reviews' => 3521,
        'stock' => 12,
        'free_shipping' => true,
        'badge' => 'SALE',
        'images' => [
            'https://images.unsplash.com/photo-1587202372634-32705e3bf49c?w=800',
            'https://images.unsplash.com/photo-1591488320449-011701bb6704?w=800',
            'https://images.unsplash.com/photo-1600861194942-f883de0dfe96?w=800',
            'https://images.unsplash.com/photo-1612036782180-6f0b6cd846fe?w=800',
        ],
        'description' => 'The NVIDIA GeForce RTX 4090 is the ultimate graphics card for enthusiasts and professionals. Powered by the Ada Lovelace architecture, it delivers groundbreaking performance for 4K gaming, 3D rendering, and AI workloads. With 24GB of GDDR6X memory and advanced ray tracing, experience gaming and creation like never before.',
        'features' => [
            '24GB GDDR6X High-Speed Memory',
            'Ada Lovelace Architecture',
            '16384 CUDA Cores',
            'Ray Tracing Cores 3rd Gen',
            'Tensor Cores 4th Gen with DLSS 3',
            'Boost Clock up to 2.52 GHz',
            'PCIe 4.0 Interface',
            'HDMI 2.1a and DisplayPort 1.4a',
            'Support for 8K Gaming',
            'Advanced Cooling System with Triple Fans',
            'RGB Lighting Customization',
            'NVLink Ready for Multi-GPU Setup'
        ],
        'specifications' => [
            'Model' => 'GeForce RTX 4090',
            'Memory' => '24GB GDDR6X',
            'Memory Bus' => '384-bit',
            'CUDA Cores' => '16384',
            'Boost Clock' => '2.52 GHz',
            'Ray Tracing Cores' => '128 (3rd Gen)',
            'Tensor Cores' => '512 (4th Gen)',
            'TDP' => '450W',
            'Power Connectors' => '1x 16-pin (12VHPWR)',
            'Display Outputs' => '3x DisplayPort 1.4a, 1x HDMI 2.1a',
            'Max Resolution' => '7680 x 4320',
            'DirectX Support' => 'DirectX 12 Ultimate',
            'Length' => '304mm',
            'Warranty' => '3 Years'
        ]
    ],
    [
        'id' => 3,
        'name' => 'Corsair Vengeance DDR5 32GB (2x16GB) 6000MHz RAM',
        'brand' => 'Corsair',
        'category' => 'Memory',
        'price' => 179.99,
        'old_price' => null,
        'rating' => 4.7,
        'reviews' => 1892,
        'stock' => 67,
        'free_shipping' => true,
        'badge' => 'NEW',
        'images' => [
            'https://images.unsplash.com/photo-1541029071515-84cc7e1067ca?w=800',
            'https://images.unsplash.com/photo-1562976540-1502c2145186?w=800',
            'https://images.unsplash.com/photo-1591488320449-011701bb6704?w=800',
            'https://images.unsplash.com/photo-1587202372634-32705e3bf49c?w=800',
        ],
        'description' => 'Unleash extreme performance with Corsair Vengeance DDR5 memory. Designed for high-end gaming and professional workstations, this kit delivers blazing-fast speeds of 6000MHz. Enhanced with sleek aluminum heat spreaders and dynamic RGB lighting, it combines performance with stunning aesthetics.',
        'features' => [
            '32GB Total Capacity (2x16GB)',
            'DDR5 6000MHz Speed',
            'CL36 Latency for Quick Response',
            'Intel XMP 3.0 Ready',
            'AMD EXPO™ Certified',
            'Custom Performance PCB',
            'Anodized Aluminum Heat Spreader',
            'Dynamic RGB Lighting',
            'Compatible with iCUE Software',
            'Lifetime Warranty',
            'Low-Profile Design (34mm)',
            'Tested for Stability and Performance'
        ],
        'specifications' => [
            'Model' => 'Corsair Vengeance DDR5',
            'Capacity' => '32GB (2 x 16GB)',
            'Speed' => '6000MHz',
            'Type' => 'DDR5 SDRAM',
            'CAS Latency' => 'CL36',
            'Timing' => '36-36-36-76',
            'Voltage' => '1.35V',
            'Pin Configuration' => '288-pin DIMM',
            'Heat Spreader' => 'Aluminum',
            'RGB' => 'Yes (10-zone)',
            'Profile Support' => 'Intel XMP 3.0, AMD EXPO',
            'Height' => '34mm',
            'Warranty' => 'Lifetime'
        ]
    ],
    [
        'id' => 4,
        'name' => 'Samsung 980 PRO 2TB NVMe M.2 SSD',
        'brand' => 'Samsung',
        'category' => 'Storage',
        'price' => 199.99,
        'old_price' => 249.99,
        'rating' => 4.8,
        'reviews' => 4156,
        'stock' => 89,
        'free_shipping' => true,
        'badge' => null,
        'images' => [
            'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=800',
            'https://images.unsplash.com/photo-1531492746076-161ca9bcad58?w=800',
            'https://images.unsplash.com/photo-1625948515291-69613efd103f?w=800',
            'https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?w=800',
        ],
        'description' => 'The Samsung 980 PRO delivers next-level SSD performance with PCIe 4.0 technology. Perfect for gaming, 4K video editing, and data-intensive applications, it offers sequential read speeds up to 7,000 MB/s. The intelligent thermal solution ensures sustained performance even under heavy workloads.',
        'features' => [
            '2TB Storage Capacity',
            'PCIe 4.0 NVMe Interface',
            'Sequential Read: up to 7,000 MB/s',
            'Sequential Write: up to 5,100 MB/s',
            'Random Read: up to 1,000K IOPS',
            'Random Write: up to 1,000K IOPS',
            'Samsung V-NAND Technology',
            'Intelligent TurboWrite 2.0',
            'Dynamic Thermal Guard Protection',
            'AES 256-bit Encryption',
            'M.2 2280 Form Factor',
            '5-Year Limited Warranty'
        ],
        'specifications' => [
            'Model' => 'Samsung 980 PRO',
            'Capacity' => '2TB',
            'Interface' => 'PCIe 4.0 x4, NVMe 1.3c',
            'Form Factor' => 'M.2 2280',
            'Sequential Read' => 'Up to 7,000 MB/s',
            'Sequential Write' => 'Up to 5,100 MB/s',
            'Random Read' => 'Up to 1,000K IOPS',
            'Random Write' => 'Up to 1,000K IOPS',
            'NAND Type' => 'Samsung V-NAND 3-bit MLC',
            'Controller' => 'Samsung Elpis',
            'DRAM' => '2GB LPDDR4',
            'TBW' => '1,200 TB',
            'Power Consumption' => '5.7W (Max)',
            'Warranty' => '5 Years'
        ]
    ],
    [
        'id' => 5,
        'name' => 'ASUS ROG Strix X670E-E Gaming WiFi Motherboard',
        'brand' => 'ASUS',
        'category' => 'Motherboards',
        'price' => 499.99,
        'old_price' => 599.99,
        'rating' => 4.6,
        'reviews' => 987,
        'stock' => 23,
        'free_shipping' => true,
        'badge' => 'HOT',
        'images' => [
            'https://images.unsplash.com/photo-1563191165-e77926d22e54?w=800',
            'https://images.unsplash.com/photo-1562976540-1502c2145186?w=800',
            'https://images.unsplash.com/photo-1600861194942-f883de0dfe96?w=800',
            'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800',
        ],
        'description' => 'The ASUS ROG Strix X670E-E Gaming WiFi motherboard is engineered for AMD Ryzen 7000 Series processors. Featuring robust power delivery, PCIe 5.0 support, and comprehensive cooling, it\'s designed for extreme gaming and content creation. With WiFi 6E, premium audio, and customizable RGB lighting, it delivers the complete enthusiast experience.',
        'features' => [
            'AMD X670E Chipset',
            'Socket AM5 for Ryzen 7000 Series',
            'DDR5 Memory Support up to 6400MHz',
            'PCIe 5.0 Ready (x16 + M.2)',
            '18+2 Power Stages with ProCool II',
            'WiFi 6E (802.11ax) + Bluetooth 5.2',
            '2.5Gb Ethernet',
            'SupremeFX 7.1 Surround Sound',
            'Aura Sync RGB Lighting',
            'AI Overclocking and Cooling',
            'BIOS FlashBack Button',
            'Comprehensive I/O Shield'
        ],
        'specifications' => [
            'Model' => 'ROG Strix X670E-E Gaming WiFi',
            'Chipset' => 'AMD X670E',
            'CPU Socket' => 'AM5',
            'Memory Slots' => '4 x DDR5 (Max 128GB)',
            'Memory Speed' => 'Up to DDR5-6400 (OC)',
            'PCIe Slots' => '2 x PCIe 5.0 x16, 1 x PCIe 4.0 x4',
            'M.2 Slots' => '4 x M.2 (PCIe 5.0/4.0)',
            'SATA Ports' => '4 x SATA 6Gb/s',
            'USB Ports' => '1 x USB 3.2 Gen 2x2 Type-C, 8 x USB 3.2',
            'LAN' => 'Intel 2.5Gb Ethernet',
            'Wireless' => 'WiFi 6E + BT 5.2',
            'Audio' => 'SupremeFX 7.1',
            'Form Factor' => 'ATX',
            'Warranty' => '3 Years'
        ]
    ]
];
?>